starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
starting iteration 0 of 1
Instance is healthy. All health checks are passing.
/home/node/test_load.js:171
        throw new Error(err);
              ^

Error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ could not load https://premier-janot-mathready-d26aed83.koyeb.app/app/play_finish/notNonMember/guest/tt_easy_click_answer/0/mixed/1 due to TypeError: fetch failed journey 11 aaaaaaa bbbbbbbb
    at /home/node/test_load.js:171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.15.0
/home/node/test_load.js:171
        throw new Error(err);
              ^

Error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ could not load https://premier-janot-mathready-d26aed83.koyeb.app/app/play_finish/notNonMember/guest/tt_easy_click_answer/0/mixed/1 due to TypeError: fetch failed journey 16 aaaaaaa bbbbbbbb
    at /home/node/test_load.js:171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.15.0
/home/node/test_load.js:171
        throw new Error(err);
              ^

Error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ could not load https://premier-janot-mathready-d26aed83.koyeb.app/app/play_finish/notNonMember/guest/tt_easy_click_answer/0/mixed/1 due to TypeError: fetch failed journey 3 aaaaaaa bbbbbbbb
    at /home/node/test_load.js:171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.15.0
/home/node/test_load.js:171
        throw new Error(err);
              ^

Error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ could not load https://premier-janot-mathready-d26aed83.koyeb.app/app/play_finish/notNonMember/guest/tt_easy_click_answer/0/mixed/1 due to TypeError: fetch failed journey 7 aaaaaaa bbbbbbbb
    at /home/node/test_load.js:171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.15.0
/home/node/test_load.js:171
        throw new Error(err);
              ^

Error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ could not load https://premier-janot-mathready-d26aed83.koyeb.app/app/play_finish/notNonMember/guest/tt_easy_click_answer/0/mixed/1 due to TypeError: fetch failed journey 10 aaaaaaa bbbbbbbb
    at /home/node/test_load.js:171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.15.0
/home/node/test_load.js:171
        throw new Error(err);
              ^

Error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ could not load https://premier-janot-mathready-d26aed83.koyeb.app/app/play_finish/notNonMember/guest/tt_easy_click_answer/0/mixed/1 due to TypeError: fetch failed journey 14 aaaaaaa bbbbbbbb
    at /home/node/test_load.js:171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.15.0
/home/node/test_load.js:171
        throw new Error(err);
              ^

Error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ could not load https://premier-janot-mathready-d26aed83.koyeb.app/app/play_finish/notNonMember/guest/tt_easy_click_answer/0/mixed/1 due to TypeError: fetch failed journey 7 aaaaaaa bbbbbbbb
    at /home/node/test_load.js:171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.15.0
/home/node/test_load.js:171
        throw new Error(err);
              ^

Error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ could not load https://premier-janot-mathready-d26aed83.koyeb.app/app/play_finish/notNonMember/guest/tt_easy_click_answer/0/mixed/1 due to TypeError: fetch failed journey 15 aaaaaaa bbbbbbbb
    at /home/node/test_load.js:171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.15.0
/home/node/test_load.js:171
        throw new Error(err);
              ^

Error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ could not load https://premier-janot-mathready-d26aed83.koyeb.app/app/play_finish/notNonMember/guest/tt_easy_click_answer/0/mixed/1 due to TypeError: fetch failed journey 10 aaaaaaa bbbbbbbb
    at /home/node/test_load.js:171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.15.0
/home/node/test_load.js:171
        throw new Error(err);
              ^

Error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ could not load https://premier-janot-mathready-d26aed83.koyeb.app/app/play_finish/notNonMember/guest/tt_easy_click_answer/0/mixed/1 due to TypeError: fetch failed journey 13 aaaaaaa bbbbbbbb
    at /home/node/test_load.js:171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.15.0
/home/node/test_load.js:171
        throw new Error(err);
              ^

Error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ could not load https://premier-janot-mathready-d26aed83.koyeb.app/app/play_finish/notNonMember/guest/tt_easy_click_answer/0/mixed/1 due to TypeError: fetch failed journey 20 aaaaaaa bbbbbbbb
    at /home/node/test_load.js:171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.15.0
/home/node/test_load.js:171
        throw new Error(err);
              ^

Error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ could not load https://premier-janot-mathready-d26aed83.koyeb.app/app/play_finish/notNonMember/guest/tt_easy_click_answer/0/mixed/1 due to TypeError: fetch failed journey 18 aaaaaaa bbbbbbbb
    at /home/node/test_load.js:171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.15.0
/home/node/test_load.js:171
        throw new Error(err);
              ^

Error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ could not load https://premier-janot-mathready-d26aed83.koyeb.app/app/play_finish/notNonMember/guest/tt_easy_click_answer/0/mixed/1 due to TypeError: fetch failed journey 5 aaaaaaa bbbbbbbb
    at /home/node/test_load.js:171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.15.0
/home/node/test_load.js:171
        throw new Error(err);
              ^

Error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ could not load https://premier-janot-mathready-d26aed83.koyeb.app/app/play_finish/notNonMember/guest/tt_easy_click_answer/0/mixed/1 due to TypeError: fetch failed journey 16 aaaaaaa bbbbbbbb
    at /home/node/test_load.js:171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.15.0
/home/node/test_load.js:171
        throw new Error(err);
              ^

Error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ could not load https://premier-janot-mathready-d26aed83.koyeb.app/app/play_finish/notNonMember/guest/tt_easy_click_answer/0/mixed/1 due to TypeError: fetch failed journey 13 aaaaaaa bbbbbbbb
    at /home/node/test_load.js:171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.15.0
/home/node/test_load.js:171
        throw new Error(err);
              ^

Error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ could not load https://premier-janot-mathready-d26aed83.koyeb.app/app/play_finish/notNonMember/guest/tt_easy_click_answer/0/mixed/1 due to TypeError: fetch failed journey 5 aaaaaaa bbbbbbbb
    at /home/node/test_load.js:171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.15.0
/home/node/test_load.js:171
        throw new Error(err);
              ^

Error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ could not load https://premier-janot-mathready-d26aed83.koyeb.app/app/play_finish/notNonMember/guest/tt_easy_click_answer/0/mixed/1 due to TypeError: fetch failed journey 19 aaaaaaa bbbbbbbb
    at /home/node/test_load.js:171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.15.0
/home/node/test_load.js:171
        throw new Error(err);
              ^

Error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ could not load https://premier-janot-mathready-d26aed83.koyeb.app/app/play_finish/notNonMember/guest/tt_easy_click_answer/0/mixed/1 due to TypeError: fetch failed journey 3 aaaaaaa bbbbbbbb
    at /home/node/test_load.js:171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.15.0
/home/node/test_load.js:171
        throw new Error(err);
              ^

Error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ could not load https://premier-janot-mathready-d26aed83.koyeb.app/app/play_finish/notNonMember/guest/tt_easy_click_answer/0/mixed/1 due to TypeError: fetch failed journey 17 aaaaaaa bbbbbbbb
    at /home/node/test_load.js:171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.15.0
/home/node/test_load.js:171
        throw new Error(err);
              ^

Error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ could not load https://premier-janot-mathready-d26aed83.koyeb.app/app/play_finish/notNonMember/guest/tt_easy_click_answer/0/mixed/1 due to TypeError: fetch failed journey 12 aaaaaaa bbbbbbbb
    at /home/node/test_load.js:171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.15.0
/home/node/test_load.js:171
        throw new Error(err);
              ^

Error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ could not load https://premier-janot-mathready-d26aed83.koyeb.app/app/play_finish/notNonMember/guest/tt_easy_click_answer/0/mixed/1 due to TypeError: fetch failed journey 7 aaaaaaa bbbbbbbb
    at /home/node/test_load.js:171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.15.0
/home/node/test_load.js:171
        throw new Error(err);
              ^

Error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ could not load https://premier-janot-mathready-d26aed83.koyeb.app/app/play_finish/notNonMember/guest/tt_easy_click_answer/0/mixed/1 due to TypeError: fetch failed journey 13 aaaaaaa bbbbbbbb
    at /home/node/test_load.js:171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.15.0
/home/node/test_load.js:171
        throw new Error(err);
              ^

Error: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ could not load https://premier-janot-mathready-d26aed83.koyeb.app/app/play_finish/notNonMember/guest/tt_easy_click_answer/0/mixed/1 due to TypeError: fetch failed journey 3 aaaaaaa bbbbbbbb
    at /home/node/test_load.js:171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 15 at Sun May 04 2025 06:42:02 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 13 at Sun May 04 2025 06:42:08 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 9 at Sun May 04 2025 06:42:07 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 12 at Sun May 04 2025 06:42:07 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 6 at Sun May 04 2025 06:42:10 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 5 at Sun May 04 2025 06:42:11 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 2 at Sun May 04 2025 06:42:10 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 2 at Sun May 04 2025 06:42:12 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 6 at Sun May 04 2025 06:42:12 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 3 at Sun May 04 2025 06:42:10 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 9 at Sun May 04 2025 06:42:13 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 1 at Sun May 04 2025 06:42:13 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 11 at Sun May 04 2025 06:42:12 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 16 at Sun May 04 2025 06:42:13 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 11 at Sun May 04 2025 06:42:13 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 19 at Sun May 04 2025 06:42:12 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 20 at Sun May 04 2025 06:42:14 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 10 at Sun May 04 2025 06:42:13 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 5 at Sun May 04 2025 06:42:12 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 10 at Sun May 04 2025 06:42:06 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 18 at Sun May 04 2025 06:42:14 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 10 at Sun May 04 2025 06:42:14 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 13 at Sun May 04 2025 06:42:14 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 3 at Sun May 04 2025 06:42:15 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 5 at Sun May 04 2025 06:42:14 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 13 at Sun May 04 2025 06:42:15 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 5 at Sun May 04 2025 06:42:14 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 15 at Sun May 04 2025 06:42:14 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 15 at Sun May 04 2025 06:42:13 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 17 at Sun May 04 2025 06:42:14 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 14 at Sun May 04 2025 06:42:14 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 4 at Sun May 04 2025 06:42:12 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 11 at Sun May 04 2025 06:42:12 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 2 at Sun May 04 2025 06:42:15 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 16 at Sun May 04 2025 06:42:15 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 14 at Sun May 04 2025 06:42:16 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 8 at Sun May 04 2025 06:42:13 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 19 at Sun May 04 2025 06:42:15 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 11 at Sun May 04 2025 06:42:14 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 1 at Sun May 04 2025 06:42:18 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 13 at Sun May 04 2025 06:42:17 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 15 at Sun May 04 2025 06:42:16 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 3 at Sun May 04 2025 06:42:16 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 4 at Sun May 04 2025 06:42:16 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 10 at Sun May 04 2025 06:42:16 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 14 at Sun May 04 2025 06:42:18 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 6 at Sun May 04 2025 06:42:19 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 8 at Sun May 04 2025 06:42:18 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 14 at Sun May 04 2025 06:42:20 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForActivity journey 18 at Sun May 04 2025 06:42:24 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at process.processTimers (node:internal/timers:523:7)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
receive msg
receive msg
receive msg
receive msg
receive msg
receive msg
receive msg
receive msg
receive msg
receive msg
receive msg
/home/node/dom-utils.js:63
    throw new Error(error);
          ^

Error: wait condition timed out for step WaitForNewGame journey 0 at Sun May 04 2025 06:40:56 aaaaaaa bbbbbbbb
    at mandatory_wait (/home/node/dom-utils.js:63:11)
    at async do_bus_step_wait (/home/node/test_load.js:379:5)

Node.js v22.15.0
Instance is stopping.
npm error path /home/node
npm error command failed
npm error signal SIGTERM
npm error command sh -c node index.js
npm error A complete log of this run can be found in: /root/.npm/_logs/2025-05-04T06_39_38_419Z-debug-0.log
Instance stopped.
